name: Windows Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0' # 也可以改成 5.15.2
      - name: Install OpenCV
        run: |
          vcpkg install opencv:x64-windows
          # 告诉 CMake vcpkg 的安装路径
          echo "CMAKE_PREFIX_PATH=C:/vcpkg/installed/x64-windows" >> $GITHUB_ENV
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release --target jumpbox
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: jumpbox-windows
          path: build/Release/*.exe